<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-13T06:11:53Z" name="Suite" finished-at="2024-09-13T06:12:38Z" duration-ms="44301">
    <groups>
    </groups>
    <test started-at="2024-09-13T06:11:53Z" name="Test" finished-at="2024-09-13T06:12:38Z" duration-ms="44301">
      <class name="com.LoginTest">
        <test-method signature="login(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.LoginTest@6d60fe40]" started-at="2024-09-13T06:11:57Z" name="login" data-provider="dp" finished-at="2024-09-13T06:12:05Z" duration-ms="8295" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Invalid]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Invalid]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[User or Password is not valid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="login(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.LoginTest@6d60fe40]" started-at="2024-09-13T06:12:05Z" name="login" data-provider="dp" finished-at="2024-09-13T06:12:12Z" duration-ms="6975" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr588442]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Invalid]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[User or Password is not valid1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [User or Password is not valid] but found [User or Password is not valid1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [User or Password is not valid] but found [User or Password is not valid1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.LoginTest.login(LoginTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="login(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.LoginTest@6d60fe40]" started-at="2024-09-13T06:12:14Z" name="login" data-provider="dp" finished-at="2024-09-13T06:12:24Z" duration-ms="10868" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Invalid]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[nugebYp]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[User or Password is not valid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="login(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.LoginTest@6d60fe40]" started-at="2024-09-13T06:12:24Z" name="login" data-provider="dp" finished-at="2024-09-13T06:12:37Z" duration-ms="13011" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr588442]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[nugebYp]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Guru99 Bank Manager HomePage1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Guru99 Bank Manager HomePage] but found [Guru99 Bank Manager HomePage1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Guru99 Bank Manager HomePage] but found [Guru99 Bank Manager HomePage1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.LoginTest.login(LoginTest.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- com.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
